### ISSUE TITLE
facing this issue and cause stuck threads

### ISSUE THREAD

**Issue by kmadined** [spotify/threaddump-analyzer#11]

**Comment by kmadined** [comment]
"GC Daemon" #13 daemon prio=2 os_prio=0 tid=0x00007fd2a859f000 nid=0x955 in Object.wait() [0x00007fd290659000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x000000070006f990> (a sun.misc.GC$LatencyLock)
        at sun.misc.GC$Daemon.run(GC.java:117)
        - locked <0x000000070006f990> (a sun.misc.GC$LatencyLock)

"vfabric-license-heartbeat" #12 daemon prio=5 os_prio=0 tid=0x00007fd2a850b800 nid=0x94e in Object.wait() [0x00007fd290b73000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x000000070006fb20> (a java.util.TaskQueue)
        at java.util.TimerThread.mainLoop(Timer.java:552)
        - locked <0x000000070006fb20> (a java.util.TaskQueue)
        at java.util.TimerThread.run(Timer.java:505)

Please suggest on these thread dumps.

**Comment by walles** [comment]
I don't understand your issue.
1. What thread dump did you analyze?
2. What did the Thread Dump Analyzer show when you did that?
3. What did you expect the Thread Dump Analyzer to show instead?

Note that if this your Java app misbehaving you should contact your Java app vendor.
