### ISSUE TITLE
tool doesn't seem to be working for java9 jstack output

### ISSUE THREAD

**Issue by kilokahn** [spotify/threaddump-analyzer#14]
Hi guys,

Thanks for the wonderful tool. I was trying it out for the java9 jstack output (attached) and the tool doesn't seem to be doing anything, I tried it for a java8 jstack as well and it still doesn't respond. Can you please see if I am missing something obvious here?

Thanks!
[sample-jstack.txt](https://github.com/spotify/threaddump-analyzer/files/1407350/sample-jstack.txt)

**Comment by walles** [comment]
Seems to work for me with your example thread dump, can you post a screenshot of what you're getting?

![skarmavbild 2017-10-23 kl 16 40 10](https://user-images.githubusercontent.com/158201/31895230-ed55f042-b810-11e7-943e-09c657d4b002.png)

**Comment by kilokahn** [comment]
Thanks for the reply @walles - it was my adblocker that was being (over)smart here and blocking the load of `analyze.js`. So it was not a problem per-se. Thanks and apologies for the trouble!
