### ISSUE TITLE
Performance issue because of the following thread in the production

### ISSUE THREAD

**Issue by ghost** [spotify/threaddump-analyzer#5]
Hi,
I am system administrator and am not aware of java and analysis the thread dump that is causing high CPU utilization in one of the production environment. I have implemented the script in linux environment to get the cpu wise thread report and found out the thread which is causing the issue. I have done some study in the google and seems like the issue with xalan jar file where we are using both the minor and majar version in the server [ xalan2.7.0.jar & xalan2.7.1.jar]. 
Please can someone help me in resolve this issue.

> > > > "ajp-bio-8649-exec-147" daemon prio=10 tid=0x00000000432f6000 nid=0xe41b runnable [0x00007f37f4bd0000]
> > > >    java.lang.Thread.State: RUNNABLE
> > > >         at org.apache.xml.dtm.ref.dom2dtm.DOM2DTM.addNode(DOM2DTM.java:235)
> > > >         at org.apache.xml.dtm.ref.dom2dtm.DOM2DTM.nextNode(DOM2DTM.java:539)
> > > >         at org.apache.xml.dtm.ref.dom2dtm.DOM2DTM.getHandleFromNode(DOM2DTM.java:676)
> > > >         at org.apache.xml.dtm.ref.dom2dtm.DOM2DTM.getHandleOfNode(DOM2DTM.java:728)
> > > >         at org.apache.xml.dtm.ref.DTMManagerDefault.getDTMHandleFromNode(DTMManagerDefault.java:571)
> > > >         - locked <0x00007f388d7b4d08> (a org.apache.xml.dtm.ref.DTMManagerDefault)
> > > >         at org.apache.xpath.XPathContext.getDTMHandleFromNode(XPathContext.java:182)
> > > >         at org.apache.xpath.XPathAPI.eval(XPathAPI.java:236)
> > > >         at org.apache.xpath.XPathAPI.selectNodeIterator(XPathAPI.java:126)
> > > >         at org.apache.xpath.XPathAPI.selectNodeIterator(XPathAPI.java:106)
> > > >         at com.ezdata.xml.XMLHelper.selectNodes(XMLHelper.java:589)
> > > >         at com.ezdata.xml.XMLHelper.selectSingleNode(XMLHelper.java:593)
> > > >         at com.ezdata.cdsportal.web.ColumnStatistic.writeSummarySubTotal(ColumnStatistic.java:695)
> > > >         at com.ezdata.cdsportal.web.ColumnStatistic.writeSubTotal(ColumnStatistic.java:384)
> > > >         at com.ezdata.web.framework.tags.data.BaseStatistic.writeSubTotal(BaseStatistic.java:205)
> > > >         at com.ezdata.cdsportal.web.ColumnStatistic.writeSubTotal(ColumnStatistic.java:369)
> > > >         at com.ezdata.web.framework.tags.data.BaseStatistic.onSubTotal(BaseStatistic.java:157)
> > > >         at com.ezdata.cdsportal.web.ColumnStatistic.onSubTotal(ColumnStatistic.java:352)
> > > >         at com.ezdata.cdsportal.web.dynreport.ReportRunner.beforeItems(ReportRunner.java:1396)
> > > >         at com.ezdata.web.XMLEvent.fire(XMLEvent.java:149)
> > > >         at com.ezdata.web.WebEventObject._fire(WebEventObject.java:183)
> > > >         at com.ezdata.web.WebEventObject.fire(WebEventObject.java:113)
> > > >         at com.ezdata.cdsportal.web.Application.genSpreadSheet(Application.java:2564)
> > > >         at com.ezdata.web.PageEngine.loadObject(PageEngine.java:1038)
> > > >         at com.ezdata.web.component.WindowComponent.run(WindowComponent.java:128)
> > > >         at com.ezdata.web.component.WindowComponent.run(WindowComponent.java:73)
> > > >         at com.ezdata.web.PageEngine.loadObject(PageEngine.java:1036)
> > > >         at com.ezdata.web.PageEngine.processCDSForm(PageEngine.java:1466)
> > > >         at com.ezdata.web.PageEngine.loadFormWithException(PageEngine.java:1196)
> > > >         at com.ezdata.web.PageEngine.loadFormWithException(PageEngine.java:1148)
> > > >         at com.ezdata.web.PageEngine.loadForm(PageEngine.java:1237)
> > > >         at com.ezdata.web.PageEngine.loadForm(PageEngine.java:1227)
> > > >         at com.ezdata.web.PageEngine.run(PageEngine.java:820)
> > > >         at com.ezdata.cdsportal.cdsApp.processRequest(cdsApp.java:142)
> > > >         at com.ezdata.cdsportal.cdsApp.doGet(cdsApp.java:211)
> > > >         at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
> > > >         at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
> > > >         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
> > > >         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
> > > >         at com.ezdata.web.filter.ReportFilter.doFilter(ReportFilter.java:142)
> > > >         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
> > > >         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
> > > >         at com.ezdata.web.framework.session.SessionFilter$2.exec(SessionFilter.java:239)
> > > >         at com.ezdata.base.resource.ResourceManager.run(ResourceManager.java:184)
> > > >         at com.ezdata.web.framework.session.SessionFilter.doFilter(SessionFilter.java:207)
> > > >         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
> > > >         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
> > > >         at com.ezdata.web.filter.CheckReclick.processRequest(CheckReclick.java:91)
> > > >         at com.ezdata.web.filter.CheckReclickFilter.processFilter(CheckReclickFilter.java:31)
> > > >         at com.ezdata.web.filter.AbstractFilter.doFilter(AbstractFilter.java:46)
> > > >         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
> > > >         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
> > > >         at com.ezdata.smartoffice.session.SSOLoginFilter.doFilter(SSOLoginFilter.java:175)
> > > >         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
> > > >         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
> > > >         at com.ezdata.web.filter.GZIPFilter.doFilter(GZIPFilter.java:46)
> > > >         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
> > > >         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
> > > >         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
> > > >         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
> > > >         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
> > > >         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
> > > >         at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:929)
> > > >         at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:309)
> > > >         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
> > > >         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
> > > >         at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:200)
> > > >         at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585)
> > > >         at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
> > > >         - locked <0x00007f38198b2788> (a org.apache.tomcat.util.net.SocketWrapper)
> > > >         at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
> > > >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
> > > >         at java.lang.Thread.run(Thread.java:619)

**Comment by walles** [comment]
If you're having problems with Xalan, I suggest asking in a Xalan forum.

This is the bug tracker for the thread dump analyzer, and since it seems to be working fine for you I'll just close this ticket.

  Regards /Johan
